#服务信息配置
server:
  servlet:
    #访问路径设置
    context-path: /
# 应用名称
spring:
  profiles:
    active: @profileActive@ #配置环境文件
  application:
    name: uaa
  # 返回报文json配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #配置返回日期格式
    time-zone: GMT+8 #配置时间区
    default-property-inclusion: non_empty #非空属性才返回
#thymelea模板配置
thymeleaf:
  #热部署文件，页面不产生缓存，及时更新
  cache: false
  suffix: .html
  mode: HTML5
#mybatis配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志输出
  global-config:
    db-config:
      update-strategy: ignored #字段更新忽略null判断
#配置eureka注册中心服务的status信息
info:
  name: my uaa server
#日志配置
logging:
  pattern:
    file: '%date [traceId=%X{traceId}] %level %logger %file.%M:%line => %msg%n'
    console: '%date [traceId=%X{traceId}] %level %logger %file.%M:%line => %msg%n'