#服务信息配置
server:
  port: 8003
#spring配置
spring:
  #数据库配置
  datasource:
    druid:
      db-type: mysql #数据库类型
      url: jdbc:mysql://192.168.1.130:3306/uaa?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      username: uaa
      password: ENC(FYI+VwCCxFQJmU7EeLCgw7CewV+hznTf)
  #redis配置
  redis:
    key-project-name : MY-UAA #redis的key项目名称
    password: ENC(FYI+VwCCxFQJmU7EeLCgw7CewV+hznTf)
    #sentile配置
    sentinel:
      master: mymaster
      nodes: 192.168.1.130:26379,192.168.1.131:26379,192.168.1.132:26379
#eureka配置
eureka:
  client:
    service-url:
      #配置eureka集群地址
      defaultZone : http://www:www362412@192.168.1.130:8002/eureka/,http://www:www362412@192.168.1.131:8002/eureka/,http://www:www362412@192.168.1.132:8002/eureka/ #注册中心地址
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port} #该实例注册到服务中心的唯一ID
    prefer-ip-address: true #该实例，相较于hostname是否优先使用IP
#oauth2配置
security:
  oauth2:
    authorization:
      jwt:
        key-value: wenzday #jwt令牌签名