#服务器配置
server:
  servlet:
    #访问路径设置
    context-path: /blog

spring:
  profiles:
    #配置环境文件
    active: @profileActive@
  application:
    name: my-blog-server
  #数据库配置
  datasource:
    druid:
      db-type: mysql #数据库类型
      url: jdbc:mysql://192.168.1.130:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      username: blog
      password: ENC(FYI+VwCCxFQJmU7EeLCgw7CewV+hznTf)
  #redis配置
  redis:
    password: ENC(FYI+VwCCxFQJmU7EeLCgw7CewV+hznTf)
    #sentile配置
    sentinel:
      master: mymaster
      nodes: 192.168.1.130:26379,192.168.1.131:26379,192.168.1.132:26379