#本地开发配置
#服务器配置
server:
  port: 8080
#spring配置
spring:
  servlet:
    #文件上传配置
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
    #数据库配置
  datasource:
    druid:
      db-type: mysql #数据库类型
      url: jdbc:mysql://192.168.1.130:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      username: blog
      password: ENC(FYI+VwCCxFQJmU7EeLCgw7CewV+hznTf)
    #redis配置
  redis:
    password: ENC(FYI+VwCCxFQJmU7EeLCgw7CewV+hznTf)
    #sentile配置
    sentinel:
      master: mymaster
      nodes: 192.168.1.130:26379,192.168.1.131:26379,192.168.1.132:26379
#配置文件路径
file:
  imgUrlPath: /imgs/** #配置访问图片的相对路径
  imgSavePath : D:\WorkSpaces\temp\${spring.application.name}\img\ #图片保存的绝对路径，window的路径必须是\且路径最后也需要\
  otherUrlPath: /file/** #配置访问图片外其他文件的相对路径
  otherSavePath : D:\WorkSpaces\temp\${spring.application.name}\file\ #图片外其他文件保存的绝对路径，window的路径必须是\且路径最后也需要\
#eureka配置
eureka:
  client:
    service-url:
      #配置eureka集群地址
      defaultZone : http://www:www362412@localhost:8002/eureka/ #注册中心地址
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port} #该实例注册到服务中心的唯一ID
    prefer-ip-address: true #该实例，相较于hostname是否优先使用IP
#security安全配置
security:
  oauth2:
    authorization:
      jwt:
        key-value: wenzday #oauth2的jwt签名

