/**1、用户信息*/
CREATE TABLE IF NOT EXISTS SYS_USER (
	SU_ID BIGINT AUTO_INCREMENT COMMENT '用户主键ID',
	USER_ID VARCHAR(40) NOT NULL UNIQUE COMMENT '用户名',
	USER_NAME VARCHAR(100) NOT NULL COMMENT '用户昵称',
	PASS_WORD VARCHAR(200) NOT NULL COMMENT '密码',
	PHONE_NUM VARCHAR(11) COMMENT '手机号',
	BIRTHDAY DATE COMMENT '生日',
	SEX CHAR(1) COMMENT '性别：1男0女',
	PHOTO VARCHAR(256) COMMENT '头像',
	E_MAIL VARCHAR(100) COMMENT '邮箱',
    BRIEF VARCHAR(256) COMMENT '个人简介',
	STATE_CD CHAR(1) NOT NULL DEFAULT '1' COMMENT '用户状态：1有效，2注销，3封号',
    NOT_EXPIRED CHAR(1) NOT NULL DEFAULT '1' COMMENT '是否未过期。默认为1未过期，0过期',
    NOT_LOCKED CHAR(1) NOT NULL DEFAULT '1' COMMENT '账号是否未锁定。默认为1未锁定，0锁定',
    CREDENTIALS_NOT_EXPIRED CHAR(1) NOT NULL DEFAULT '1' COMMENT '证书（密码）是否未过期。默认为1未过期，0过期',
	SYS_UPDATE_TIME DATETIME COMMENT '更新时间',
	SYS_CREATE_TIME DATETIME COMMENT '创建时间',
	PRIMARY KEY(SU_ID) );
ALTER TABLE SYS_USER COMMENT '用户信息';
ALTER TABLE SYS_USER AUTO_INCREMENT=1000;
CREATE INDEX INDEX_USER_ID ON SYS_USER (USER_ID);
CREATE INDEX INDEX_USER_NAME ON SYS_USER (USER_NAME);
CREATE INDEX INDEX_STATE_CD ON SYS_USER (STATE_CD);
/**2、角色信息*/
CREATE TABLE IF NOT EXISTS SYS_ROLE (
    ROLE_ID BIGINT AUTO_INCREMENT COMMENT '角色主键',
	ROLE_CODE VARCHAR(100) NOT NULL COMMENT '角色编码',
    ROLE_NAME VARCHAR(256) NOT NULL COMMENT '角色名称',
	SYS_UPDATE_TIME DATETIME COMMENT '更新时间',
	SYS_CREATE_TIME DATETIME COMMENT '创建时间',
	PRIMARY KEY(ROLE_ID) );
ALTER TABLE SYS_ROLE COMMENT '角色信息';
CREATE INDEX INDEX_ROLE_NAME ON SYS_ROLE (ROLE_CODE);
/**3、用户角色信息*/
CREATE TABLE IF NOT EXISTS SYS_USER_ROLE (
	SUR_ID BIGINT AUTO_INCREMENT COMMENT '用户角色主键',
    SU_ID VARCHAR(40) NOT NULL COMMENT '用户主键ID',
	ROLE_ID BIGINT COMMENT '角色ID',
	SYS_UPDATE_TIME DATETIME COMMENT '更新时间',
	SYS_CREATE_TIME DATETIME COMMENT '创建时间',
	PRIMARY KEY(SUR_ID) );
ALTER TABLE SYS_USER_ROLE COMMENT '用户角色信息';
CREATE INDEX INDEX_USER_ID ON SYS_USER_ROLE (SU_ID);
CREATE INDEX INDEX_ROLE_ID ON SYS_USER_ROLE (ROLE_ID);
/**4、客户端信息*/
CREATE TABLE IF NOT EXISTS OAUTH_CLIENT_DETAILS (
    CLIENT_ID VARCHAR(48) NOT NULL UNIQUE COMMENT '客户端ID',
    RESOURCE_IDS VARCHAR(256) COMMENT '客户端拥有的资源列表,逗号分割',
    CLIENT_SECRET VARCHAR(256) COMMENT '客户端密钥',
    SCOPE VARCHAR(256) COMMENT '允许的授权范围,逗号分割',
    AUTHORIZED_GRANT_TYPES VARCHAR(256) COMMENT '认证范围,逗号分割',
    WEB_SERVER_REDIRECT_URI VARCHAR(256) COMMENT '回调地址',
    AUTHORITIES VARCHAR(256) COMMENT '权限',
    ACCESS_TOKEN_VALIDITY INT(11) COMMENT '令牌有效时间（秒）',
    REFRESH_TOKEN_VALIDITY INT(11) COMMENT '令牌刷新后有效时间（秒）',
    ADDITIONAL_INFORMATION VARCHAR(4096) COMMENT '客户端描述信息',
    AUTOAPPROVE VARCHAR(256) COMMENT '是否跳转授权页面',
    SYS_UPDATE_TIME DATETIME COMMENT '更新时间',
    SYS_CREATE_TIME DATETIME COMMENT '创建时间',
    PRIMARY KEY(CLIENT_ID) );
ALTER TABLE OAUTH_CLIENT_DETAILS COMMENT '客户端信息';

/**5、授权码信息*/
CREATE TABLE IF NOT EXISTS OAUTH_CODE (
    CODE VARCHAR(48) COMMENT '授权码',
    AUTHENTICATION BLOB COMMENT '身份验证');
ALTER TABLE OAUTH_CODE COMMENT '授权码信息';
CREATE INDEX INDEX_CODE ON OAUTH_CODE (CODE);
