/**1、插入用户信息 **/
DELETE FROM SYS_USER WHERE 1=1;
INSERT INTO SYS_USER (USER_ID, USER_NAME, PASS_WORD,STATE_CD,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('admin', '管理员', '$2a$10$.jycUozQpxha24tWaUGwFOKMI.BpZk1jw1vqydu7Q.uAnvc9wkVwy','1',now(),now());/**www362412**/
INSERT INTO SYS_USER (USER_ID, USER_NAME, PASS_WORD,STATE_CD,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('www', 'wenzday', '$2a$10$.jycUozQpxha24tWaUGwFOKMI.BpZk1jw1vqydu7Q.uAnvc9wkVwy','1',now(),now());/**www362412**/

/**2、插入角色信息 **/
DELETE FROM SYS_ROLE WHERE 1=1;
INSERT INTO SYS_ROLE (ROLE_NAME,DESCRIPTION,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('admin','管理员',now(),now());

INSERT INTO SYS_ROLE (ROLE_NAME,DESCRIPTION,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('user','用户',now(),now());

/**3、插入用户角色信息 **/
DELETE FROM SYS_USER_ROLE WHERE 1=1;
INSERT INTO SYS_USER_ROLE (USER_ID, ROLE_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('admin', (select c.ROLE_ID from sys_role c where c.ROLE_NAME='admin'),now(),now());
INSERT INTO SYS_USER_ROLE (USER_ID, ROLE_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('www', (select c.ROLE_ID from sys_role c where c.ROLE_NAME='user'),now(),now());

/**4、插入菜单信息 **/
DELETE FROM SYS_MENU WHERE 1=1;
INSERT INTO SYS_MENU (MENU_CODE,MENU_NAME,PARENT_ID,MENU_ICON,MENU_URL,MENU_ORDER,IS_DELETE,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('index','首页',null,'&#xe68e;','',0,'0',now(),now());

INSERT INTO SYS_MENU (MENU_CODE,MENU_NAME,PARENT_ID,MENU_ICON,MENU_URL,MENU_ORDER,IS_DELETE,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('userManage','用户管理',null,'&#xe612;',null,1,'0',now(),now());
INSERT INTO SYS_MENU (MENU_CODE,MENU_NAME,PARENT_ID,MENU_ICON,MENU_URL,MENU_ORDER,IS_DELETE,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('userList','用户列表',(select a.parent_id from (select m.menu_id parent_id from SYS_MENU m where m.menu_code='userManage') a),null,'',2,'0',now(),now());
INSERT INTO SYS_MENU (MENU_CODE,MENU_NAME,PARENT_ID,MENU_ICON,MENU_URL,MENU_ORDER,IS_DELETE,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('userAdd','添加用户',(select a.parent_id from (select m.menu_id parent_id  from SYS_MENU m where menu_code='userManage') a),null,'',3,'0',now(),now());

INSERT INTO SYS_MENU (MENU_CODE,MENU_NAME,PARENT_ID,MENU_ICON,MENU_URL,MENU_ORDER,MENU_TYPE,IS_DELETE,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('/find/**',null,null,null,'/find/**',0,'2','0',now(),now());
INSERT INTO SYS_MENU (MENU_CODE,MENU_NAME,PARENT_ID,MENU_ICON,MENU_URL,MENU_ORDER,MENU_TYPE,IS_DELETE,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('/test/**',null,null,null,'/test/**',0,'2','0',now(),now());

/**5、插入角色菜单信息 **/
DELETE FROM SYS_ROLE_MENU WHERE 1=1;
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='admin'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='index'),now(),now());
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='admin'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='userManage'),now(),now());
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='admin'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='userList'),now(),now());
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='admin'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='userAdd'),now(),now());

INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='admin'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='/find/**'),now(),now());
