/**1、插入用户信息 **/
DELETE FROM SYS_USER WHERE 1=1;
INSERT INTO SYS_USER (USER_ID, USER_NAME, PASS_WORD,STATE_CD,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('admin', '管理员', '$2a$10$.jycUozQpxha24tWaUGwFOKMI.BpZk1jw1vqydu7Q.uAnvc9wkVwy','1',now(),now());/**www362412**/
INSERT INTO SYS_USER (USER_ID, USER_NAME, PASS_WORD,STATE_CD,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('www', 'wenzday', '$2a$10$.jycUozQpxha24tWaUGwFOKMI.BpZk1jw1vqydu7Q.uAnvc9wkVwy','1',now(),now());/**www362412**/

/**2、插入角色信息 **/
DELETE FROM SYS_ROLE WHERE 1=1;
INSERT INTO SYS_ROLE (ROLE_NAME,DESCRIPTION,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('admin','管理员',now(),now());
INSERT INTO SYS_ROLE (ROLE_NAME,DESCRIPTION,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('user','用户',now(),now());
INSERT INTO SYS_ROLE (ROLE_NAME,DESCRIPTION,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('test','测试',now(),now());

/**3、插入用户角色信息 **/
DELETE FROM SYS_USER_ROLE WHERE 1=1;
INSERT INTO SYS_USER_ROLE (USER_ID, ROLE_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('admin', (select c.ROLE_ID from sys_role c where c.ROLE_NAME='admin'),now(),now());
INSERT INTO SYS_USER_ROLE (USER_ID, ROLE_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('www', (select c.ROLE_ID from sys_role c where c.ROLE_NAME='user'),now(),now());

/**4、插入菜单信息 **/
DELETE FROM SYS_MENU WHERE 1=1;
/**目录菜单**/
INSERT INTO SYS_MENU (MENU_CODE,MENU_URL,MENU_NAME,VUE_PATH,PARENT_ID,MENU_ICON,MENU_ORDER,MENU_TYPE,MODULE,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('home','/home','首页',null,null,'el-icon-lx-home',1,'1','admin-menu',now(),now());
INSERT INTO SYS_MENU (MENU_CODE,MENU_URL,MENU_NAME,VUE_PATH,PARENT_ID,MENU_ICON,MENU_ORDER,MENU_TYPE,MODULE,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('userInfo','/user','个人中心',null,null,'el-icon-s-custom',2,'1','admin-menu',now(),now());
INSERT INTO SYS_MENU (MENU_CODE,MENU_URL,MENU_NAME,VUE_PATH,PARENT_ID,MENU_ICON,MENU_ORDER,MENU_TYPE,MODULE,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('userList','/users','用户列表',null,null,'el-icon-user',3,'1','admin-menu',now(),now());
INSERT INTO SYS_MENU (MENU_CODE,MENU_URL,MENU_NAME,VUE_PATH,PARENT_ID,MENU_ICON,MENU_ORDER,MENU_TYPE,MODULE,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('menuManage','/menu','菜单管理',null,null,'el-icon-menu',4,'1','admin-menu',now(),now());
/**请求路径**/
INSERT INTO SYS_MENU (MENU_CODE,MENU_URL,MENU_NAME,VUE_PATH,PARENT_ID,MENU_ICON,MENU_ORDER,MENU_TYPE,MODULE,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('/user/**','/user/**','用户信息请求路径',null,null,null,null,'2','admin-security',now(),now());
INSERT INTO SYS_MENU (MENU_CODE,MENU_URL,MENU_NAME,VUE_PATH,PARENT_ID,MENU_ICON,MENU_ORDER,MENU_TYPE,MODULE,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('/common/**','/common/**','公共请求路径',null,null,null,null,'2','admin-security',now(),now());
INSERT INTO SYS_MENU (MENU_CODE,MENU_URL,MENU_NAME,VUE_PATH,PARENT_ID,MENU_ICON,MENU_ORDER,MENU_TYPE,MODULE,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('/menu/**','/menu/**','菜单请求路径',null,null,null,null,'2','admin-security',now(),now());
/**vue路由**/
INSERT INTO SYS_MENU (MENU_CODE,MENU_URL,MENU_NAME,VUE_PATH,PARENT_ID,MENU_ICON,MENU_ORDER,MENU_TYPE,MODULE,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('main','/',null,'admin/Home.vue',null,null,0,'3','admin-router',now(),now());
INSERT INTO SYS_MENU (MENU_CODE,MENU_URL,MENU_NAME,VUE_PATH,PARENT_ID,MENU_ICON,MENU_ORDER,MENU_TYPE,MODULE,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('index','/home','首页','admin/Index.vue',(SELECT M.MENU_ID FROM SYS_MENU M WHERE M.MENU_CODE='/' AND M.MODULE='admin-router'),
        null,1,'3','admin-router',now(),now());
INSERT INTO SYS_MENU (MENU_CODE,MENU_URL,MENU_NAME,VUE_PATH,PARENT_ID,MENU_ICON,MENU_ORDER,MENU_TYPE,MODULE,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('user','/user','个人中心','admin/User.vue',(SELECT M.MENU_ID FROM SYS_MENU M WHERE M.MENU_CODE='/' AND M.MODULE='admin-router'),
        null,2,'3','admin-router',now(),now());
INSERT INTO SYS_MENU (MENU_CODE,MENU_URL,MENU_NAME,VUE_PATH,PARENT_ID,MENU_ICON,MENU_ORDER,MENU_TYPE,MODULE,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('users','/users','用户列表','admin/UserList.vue',(SELECT M.MENU_ID FROM SYS_MENU M WHERE M.MENU_CODE='/' AND M.MODULE='admin-router'),
        null,3,'3','admin-router',now(),now());
INSERT INTO SYS_MENU (MENU_CODE,MENU_URL,MENU_NAME,VUE_PATH,PARENT_ID,MENU_ICON,MENU_ORDER,MENU_TYPE,MODULE,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('news','/news','消息中心','admin/News.vue',(SELECT M.MENU_ID FROM SYS_MENU M WHERE M.MENU_CODE='/' AND M.MODULE='admin-router'),
        null,4,'3','admin-router',now(),now());
INSERT INTO SYS_MENU (MENU_CODE,MENU_URL,MENU_NAME,VUE_PATH,PARENT_ID,MENU_ICON,MENU_ORDER,MENU_TYPE,MODULE,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ('menu','/menu','菜单管理','admin/MenuList.vue',(SELECT M.MENU_ID FROM SYS_MENU M WHERE M.MENU_CODE='/' AND M.MODULE='admin-router'),
        null,5,'3','admin-router',now(),now());


/**5、插入角色菜单信息 **/
DELETE FROM SYS_ROLE_MENU WHERE 1=1;
/**页面菜单**/
/** admin角色目录菜单配置 **/
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='admin'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='home' AND MODULE='admin-menu'),now(),now());
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='admin'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='userInfo' AND MODULE='admin-menu'),now(),now());
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='admin'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='userList' AND MODULE='admin-menu'),now(),now());
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='admin'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='menuManage' AND MODULE='admin-menu'),now(),now());
/** user角色目录菜单配置 **/
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='user'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='home' AND MODULE='admin-menu'),now(),now());
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='user'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='userInfo' AND MODULE='admin-menu'),now(),now());
/**请求路径**/
/** admin角色请求路径配置 **/
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='admin'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='/user/**' AND MODULE='admin-security'),now(),now());
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='admin'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='/common/**' AND MODULE='admin-security'),now(),now());
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='admin'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='/menu/**' AND MODULE='admin-security'),now(),now());
/** user角色请求路径配置 **/
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='user'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='/user/**' AND MODULE='admin-security'),now(),now());
/**vue路由**/
/** admin角色vue路由配置 **/
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='admin'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='/' AND MODULE='admin-router'),now(),now());
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='admin'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='index' AND MODULE='admin-router'),now(),now());
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='admin'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='user' AND MODULE='admin-router'),now(),now());
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='admin'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='users' AND MODULE='admin-router'),now(),now());
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='admin'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='news' AND MODULE='admin-router'),now(),now());
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='admin'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='menu' AND MODULE='admin-router'),now(),now());
/** user角色vue路由配置 **/
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='user'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='/' AND MODULE='admin-router'),now(),now());
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='user'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='index' AND MODULE='admin-router'),now(),now());
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='user'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='user' AND MODULE='admin-router'),now(),now());
INSERT INTO SYS_ROLE_MENU (ROLE_ID,MENU_ID,SYS_UPDATE_TIME,SYS_CREATE_TIME)
VALUES ((SELECT C.ROLE_ID FROM SYS_ROLE C WHERE C.ROLE_NAME='user'),
        (SELECT MENU_ID FROM SYS_MENU WHERE MENU_CODE='news' AND MODULE='admin-router'),now(),now());
