#本地开发配置
#服务器配置
server:
  port: 8001
#日志配置
logging:
  file:
    path: /home/ap/logs/${spring.application.name}/  #日志路径
#eureka配置
eureka:
  client:
    service-url:
      #配置eureka集群地址
      defaultZone : http://www:www362412@localhost:8002/eureka/ #注册中心地址
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port} #该实例注册到服务中心的唯一ID
    prefer-ip-address: true #该实例，相较于hostname是否优先使用IP
