spring:
  application:
    name: zuul-server
  profiles:
    active: @profileActive@
  servlet:
    #文件上传配置
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#zuul路由网关配置
zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis:  3000
  routes:
    #设置统一认证授权服务路径
    my-uaa.serviceId: uaa
    my-uaa.path: /uaa/**
    #设置my-base服务路径
    my-base.serviceId: my-base
    my-base.path: /base/**
    #设置my-blog服务路径
    my-blog.serviceId: my-blog
    my-blog.path: /blog/**
  ignored-services: "*" #设置不能使用spring.application.name访问
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization #配置header允许转发Cookie,Set-Cookie,Authorization包括其他自定义信息