server:
  tomcat:
    max-http-form-post-size: 50MB #设置post请求最大值
    connection-timeout: 180000
spring:
  application:
    name: zuul
  profiles:
    active: @profileActive@
  servlet:
    #文件上传配置
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#配置eureka注册中心服务的status信息
info:
  name: 网关服务
#配置ribbon超时时间解决504问题
ribbon:
  ServerListRefreshInterval: 10000 # 从注册中心刷新servelist的时间 默认30秒，单位ms
  ReadTimeout: 10000 # 请求处理的超时时间 默认1秒，单位ms
  ConnectTimeout: 10000 # 请求连接的超时时间 默认1秒，单位ms
  MaxAutoRetries: 0 # 对当前实例的重试次数 默认0
  MaxAutoRetriesNextServer: 1 # 切换实例的重试次数 默认1
#zuul路由网关配置00000000000
zuul:
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis:  30000
  routes:
    #设置统一认证授权服务路径
    my-uaa.serviceId: uaa
    my-uaa.path: /uaa/**
    #设置my-base服务路径
    my-base.serviceId: my-base
    my-base.path: /base/**
    #设置my-blog服务路径
    my-blog.serviceId: my-blog
    my-blog.path: /blog/**
  ignored-services: "*" #设置不能使用spring.application.name访问
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization #配置header允许转发Cookie,Set-Cookie,Authorization包括其他自定义信息
