#生产环境配置
#服务器配置
server:
  port: 8070
#配置文件路径
file:
  imgUrlPath: /imgs/** #配置访问图片的相对路径
  imgSavePath : /usr/local/docker/file/img/ #图片保存的绝对路径，window的路径必须是\且路径最后也需要\
  otherUrlPath: /file/** #配置访问图片外其他文件的相对路径
  otherSavePath : /usr/local/docker/file/other/ #图片外其他文件保存的绝对路径，window的路径必须是\且路径最后也需要\
#eureka配置
eureka:
  client:
    service-url:
      #配置eureka集群地址
      defaultZone : http://www:www362412@192.168.1.130:8002/eureka/,http://www:www362412@192.168.1.131:8002/eureka/,http://www:www362412@192.168.1.132:8002/eureka/ #注册中心地址
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port} #该实例注册到服务中心的唯一ID
    prefer-ip-address: true #该实例，相较于hostname是否优先使用IP
#配置eureka注册中心服务的status信息
info:
  name: my blog administrator server
spring:
  servlet:
    #文件上传配置
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB