#服务器配置
server:
  servlet:
    #访问路径设置
    context-path: /
spring:
  profiles:
    #配置环境文件
    active: @profileActive@
  application:
    name: my-admin
  #数据库配置
  datasource:
    druid:
      db-type: mysql #数据库类型
      url: jdbc:mysql://192.168.1.130:3306/admin?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      username: admin
      password: ENC(FYI+VwCCxFQJmU7EeLCgw7CewV+hznTf)
  #redis配置
  redis:
    key-project-name : MY-BLOG #redis的key项目名称
    password: ENC(FYI+VwCCxFQJmU7EeLCgw7CewV+hznTf)
    #sentile配置
    sentinel:
      master: mymaster
      nodes: 192.168.1.130:26379,192.168.1.131:26379,192.168.1.132:26379
  # 返回报文json配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #配置返回日期格式
    time-zone: GMT+8 #配置时间区
    default-property-inclusion: non_empty #非空属性才返回
#mybatis配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志输出
  global-config:
    db-config:
      update-strategy: ignored #字段更新忽略null判断
# jwt的配置
jwt:
  user-prefix : MY-BLOG:TOKEN:USER_ID #redis单点登录的token的用户key前缀
  secret-key : 6969fc2fd7e864ca8152860ca8b38e76 #token加密密钥
  expire-time-second : 1800 #token过期时间（秒）
  cookie-day : 7 #cookie免登录有效天数