#端口配置
server:
  port: 8002
#日志配置
logging:
  config: classpath:logback-dev.xml
#spring配置
spring:
  #安全认证配置
  security:
    user:
      name: www
      password: ENC(FYI+VwCCxFQJmU7EeLCgw7CewV+hznTf)
#eureka配置
eureka:
  instance:
    instance-id: ${spring-application.name}:${eureka.instance.ip-address}:${server.port} #该实例注册到服务中心的唯一ID
    prefer-ip-address: true #该实例，相较于hostname是否优先使用IP
  client:
    fetch-registry: false #此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    register-with-eureka: false #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    service-url:
      #配置eureka其他集群地址（dev环境本机地址，避免控制台报错）
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/