spring:
  application:
    name: eureka-server
  profiles:
    active: @profileActive@
#配置eureka注册中心服务的status信息
info:
  name: my blog eureka server center
#日志配置
logging:
  pattern:
    file: '%date [traceId=%X{traceId}] %level %logger{10} -> %file:%line => %msg%n'
    console: '%date [traceId=%X{traceId}] %level %logger{10} -> %file:%line => %msg%n'