#端口配置
server:
  port: 8002
#日志配置
logging:
  config: classpath:logback-prod.xml
  file:
    path: /home/ap/logs/${spring.application.name}/  #日志路径
#spring配置
spring:
  #安全认证配置
  security:
    user:
      name: www
      password: ENC(FYI+VwCCxFQJmU7EeLCgw7CewV+hznTf)
#eureka配置
eureka:
  instance:
    instance-id: ${spring-application.name}:${spring.cloud.client.ip-address}:${server.port} #该实例注册到服务中心的唯一ID
    prefer-ip-address: true #该实例，相较于hostname是否优先使用IP
  client:
    fetch-registry: false #此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    register-with-eureka: false #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    service-url:
      defaultZone: http://www:www362412@192.168.1.130:8002/eureka/,http://www:www362412@192.168.1.131:8002/eureka/ #注册中心地址
