#服务器配置
server:
  servlet:
    #访问路径设置
    context-path: /
spring:
  profiles:
    #配置环境文件
    active: @profileActive@
  application:
    name: my-base
  # 返回报文json配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #配置返回日期格式
    time-zone: GMT+8 #配置时间区
    default-property-inclusion: non_empty #非空属性才返回
#mybatis配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实现数据库下划线字段到POJO类驼峰形式的自动映射
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: ignored #字段更新忽略null判断
feign:
  hystrix:
    enabled: true #开启熔断机制
#配置ribbon超时时间解决504问题
ribbon:
  ServerListRefreshInterval: 1000 # 从注册中心刷新servelist的时间 默认30秒，单位ms
  ReadTimeout: 10000 # 请求处理的超时时间 默认1秒，单位ms
  ConnectTimeout: 10000 # 请求连接的超时时间 默认1秒，单位ms
  MaxAutoRetries: 0 # 对当前实例的重试次数 默认0
  MaxAutoRetriesNextServer: 1 # 切换实例的重试次数 默认1
# hystrix配置
hystrix:
  shareSecurityContext: true #开启共享SecurityContext
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #配置超时时间
com:
  www:
    common:
      feign: #配置需要调用的应用服务
        blog: my-blog #需要的调用的应用服务
#配置eureka注册中心服务的status信息
info:
  name: my blog administrator server