#服务器配置
server:
  servlet:
    #访问路径设置
    context-path: /

spring:
  profiles:
    #配置环境文件
    active: dev
  application:
    name: my-blog-admin
  #数据库配置
  datasource:
    druid:
      db-type: mysql #数据库类型
      url: jdbc:mysql://192.168.1.130:3306/admin?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      username: admin
      password: www362412
  #redis配置
  redis:
    password: www362412
    #sentile配置
    sentinel:
      master: mymaster
      nodes: 192.168.1.130:26379,192.168.1.131:26379,192.168.1.132:26379
#mybatis配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
